src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Cette email est déja utilisé')]
#[UniqueEntity(fields: ['no_adeli'], message: 'Ce numero Adeli est déja uttilisé')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    //Annotation/Attribut php8
    #[ORM\Id] //Signifie que c'est la cle primaire
    #[ORM\GeneratedValue] // L'id sera en auto increment
    #[ORM\Column] //Colonne id
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message: "Veuillez saisir une adresse email.")]
    #[Assert\Length(
        min: 3,
        max: 180,
        minMessage: 'Votre email doit avoir au moins {{ limit }} caracteres',
        maxMessage: 'Votre email ne doit pas depasser {{ limit }} caracteres',
    )]
    #[Assert\Email(message: 'Cette adresse email n\'est pas valide')]
    private ?string $email = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50, type: 'string')]

    #[Assert\Length(
        min: 3,
        max: 50,
        minMessage: 'Votre nom doit avoir au moins {{ limit }} caracteres',
        maxMessage: 'Votre nom ne doit pas depasser {{ limit }} caracteres',
    )]
    private ?string $last_name;


    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(
        message: 'Veuillez saisir un  nom '
    )]

    #[Assert\Length(
        min: 3,
        max: 50,
        minMessage: 'Votre prenom doit avoir au moins {{ limit }} caracteres',
        maxMessage: 'Votre prénom ne doit pas depasser {{ limit }} caracteres',
    )]
    private ?string $name;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: 'Le numéro de téléphone ne peut pas être vide')]
    #[Assert\Regex(
        pattern: '/^[0-9]{10}$/',
        message: 'Le numéro de téléphone doit contenir 10 chiffres'
    )]
    private ?string $phone = null;

    #[ORM\Column(unique: true)]
    #[Assert\NotBlank(message: 'Veuillez saisir un numéro Adeli')]
    #[Assert\Positive(message: 'Le numéro Adeli doit être un entier positif')]


    private ?int $no_adeli = null;


    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\NotBlank(message: 'L\'adresse ne peut pas être vide')]
    #[Assert\Length(
        min: 10,
        max: 100,
        minMessage: 'L\'adresse doit avoir au moins {{ limit }} caractères',
        maxMessage: 'L\'adresse ne doit pas dépasser {{ limit }} caractères'
    )]
    private ?string $address = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank(message: 'Le code postal ne peut pas être vide')]
    #[Assert\Regex(
        pattern: '/^[0-9]{5}$/',
        message: 'Le code postal doit contenir 5 chiffres'
    )]
    private ?int $zipcode = null;


    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\NotBlank(message: 'La ville ne peut pas être vide')]
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Le nom de la ville doit avoir au moins {{ limit }} caractères',
        maxMessage: 'Le nom de la ville ne doit pas dépasser {{ limit }} caractères'
    )]
    private ?string $city = null;




    //Attributs non utilisé dans le formulaire d'inscription   

    #[ORM\Column(type: 'json')]
    private array $roles = [];


    #[ORM\Column(type: 'boolean')]
    private ?bool $is_verified = false;


    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $resetToken;

    #[ORM\ManyToMany(targetEntity: Patient::class, mappedBy: 'users')]
    private Collection $patients;

    #[ORM\Column(type: 'datetime_immutable', options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $create_at = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $active;

    #[ORM\Column(length: 50)]
    private ?string $inscription_status = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Evaluation::class)]
    private Collection $evaluations;

    #[ORM\Column(length: 100)]
    private ?string $status = null;

    public function __construct()
    {
        $this->patients = new ArrayCollection();
        $this->create_at = new \DateTimeImmutable();
        //Lorsqu'un utilisateur est créer il a comme status "invalide" par defaut
        $this->inscription_status = "invalide";
        //Lorsqu'un utilisateur est créer il a comme Role "ROLE_USER" par defaut
        $this->roles = ['ROLE_USER'];
        $this->active = 1; // ou une autre valeur par défaut selon vos besoins
        $this->evaluations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getResetToken()
    {
        return $this->resetToken;
    }

    /**
     * @param mixed $resetToken 
     * @return self
     */
    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;
        return $this;
    }




    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at): static
    {
        $this->create_at = $create_at;

        return $this;
    }


    /**
     * @return Collection<int, Patient>
     */
    public function getPatients(): Collection
    {
        return $this->patients;
    }

    public function addPatient(Patient $patient): static
    {
        if (!$this->patients->contains($patient)) {
            $this->patients->add($patient);
            $patient->addUser($this);
        }

        return $this;
    }

    public function removePatient(Patient $patient): static
    {
        if ($this->patients->removeElement($patient)) {
            $patient->removeUser($this);
        }

        return $this;
    }

    public function getNoAdeli(): ?int
    {
        return $this->no_adeli;
    }

    public function setNoAdeli(int $no_adeli): static
    {
        $this->no_adeli = $no_adeli;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?int
    {
        return $this->zipcode;
    }

    public function setZipcode(?int $zipcode): static
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getActive(): ?int
    {
        return $this->active;
    }

    public function setActive(int $active): static
    {
        $this->active = $active;

        return $this;
    }

    public function getInscriptionStatus(): ?string
    {
        return $this->inscription_status;
    }

    public function setInscriptionStatus(string $inscription_status): static
    {
        $this->inscription_status = $inscription_status;

        return $this;
    }

    /**
     * @return Collection<int, Evaluation>
     */

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">

		<title>
			{% block title %}Béocler
			{% endblock %}
		</title>

		<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">

		<!-- Feuilles de style -->

		{# BOOTSTRAP via le lien <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">#}

		<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}"> {% block stylesheets %}
			<link rel="stylesheet" href="{{ asset('css/_footer.css') }}">
			<link rel="stylesheet" href="{{ asset('css/_nav.css') }}">
			<link rel="stylesheet" href="{{ asset('css/main.css') }}">
			{{ encore_entry_link_tags('app') }}
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css">

		{% endblock %}


		<!-- Fichiers JS -->

		{# JS BOOTSTRAP via le lien   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
																																																																																																		#}
		<script src="{{ asset('js/bootstrap.bundle.js') }}"></script>
		<script src="{{ asset('js/jquery-3.7.1.min.js') }}"></script>

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}

		{% endblock %}

		<!-- responsive -->

		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>

	<body
		class="bg-light">
		<!-- nav bar -->
		{% block nav %}
			{% include "_partials/_nav.html.twig" %}


			<!--Conditions qui verifie que l'user est connecté est que sont compte n'a pas encore étais activé-->
			{% if app.user and app.user.isVerified == false %}
				<!--On va afficher une alerte-->
				<div class="alert alert-warning alert-dismissible" role="alert">
					<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

					<div class="alert-message">
						<strong>Votre compte n'est pas activé</strong>,<a href="{{ path('resend_verif') }}">renvoyer le lien d'activation</a>
					</div>
				</div>
			{% endif %}

			{% include "_partials/_flash.html.twig" %}
		{% endblock %}


		<!-- body -->
		{% block body %}{% endblock %}

		<!-- footer -->
		{% block footer %}
			{% include "_partials/_footer.html.twig" %}
		{% endblock %}

	</body>

</html>

templates/users.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Profile
			{% endblock %}
		</title>

		<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/axentix@0.5.3/dist/css/axentix.min.css"> {% block stylesheets %}{% endblock %}

		<link rel="stylesheet" href="{{ asset('css/styles.css') }}">
		<link rel="stylesheet" href="{{ asset('css/_footer.css') }}">

		<link rel="stylesheet" href="{{ asset('css/_nav.css') }}">
		<link rel="stylesheet" href="{{ asset('css/main.css') }}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css">

		{{ encore_entry_link_tags('app') }}


		<script src="{{ asset('js/bootstrap.bundle.js') }}"></script>
		<script src="{{ asset('js/jquery-3.7.1.min.js') }}"></script>

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}

		{% endblock %}

		<!-- responsive -->

		<meta name="viewport" content="width=device-width, initial-scale=1.0">

	</head>


	<body class="layout with-sidenav">
		<header>
			{% block nav %}
				{% include "_partials/_nav.html.twig" %}


				<!--Conditions qui verifie que l'user est connecté est que sont compte n'a pas encore étais activé-->
				{% if app.user and app.user.isVerified == false %}
					<!--On va afficher une alerte-->
					<div class="alert alert-warning alert-dismissible" role="alert">
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

						<div class="alert-message">
							<strong>Votre compte n'est pas activé</strong>,<a href="{{ path('resend_verif') }}">renvoyer le lien d'activation</a>
						</div>
					</div>
				{% endif %}


			{% endblock %}
			<!--On inclue le menu!-->
		</header>
		<div id="example-sidenav" class="sidenav large fixed white">
			<div class="sidenav-header">
				<button data-target="example-sidenav" class="sidenav-trigger">
					<i class="fas fa-times"></i>
				</button>

			</div>
			<a href="{{ path('users_index') }}" class="sidenav-link active">Mon profil</a>

		</div>
		<main>
			<button data-target="example-sidenav" class="btn press amaranth dark-1 sidenav-trigger hide-md-up">
				ouvrir navbar
			</button>
			{% block body %}{% endblock %}
		</main>

		{% include "_partials/_footer.html.twig" %}
		<!--On inclue le footer !-->


		<script src="https://cdn.jsdelivr.net/npm/axentix@0.5.3/dist/js/axentix.min.js"></script>

		<script>
			var sidenav = new Sidenav('#example-sidenav');
		</script>
		<script src="{{ asset('js/scripts.js') }}"></script>
	</body>
</html>