src/Entity/Score.php
<?php

namespace App\Entity;

use App\Repository\ScoreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ScoreRepository::class)]
class Score
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $points = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $value_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $response_name = null;

    #[ORM\Column]
    private ?bool $is_included_in_total_score = null;

    #[ORM\ManyToOne(inversedBy: 'scores')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Question $question = null;

    #[ORM\ManyToOne(inversedBy: 'scores')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Response $response = null;

    
    public function getId(): ?int
    {
        return $this->id;
    }
    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }
    public function getPoints(): ?int
    {
        return $this->points;
    }

    public function setPoints(int $points): static
    {
        $this->points = $points;

        return $this;
    }

    public function getValueName(): ?string
    {
        return $this->value_name;
    }

    public function setValueName(?string $value_name): static
    {
        $this->value_name = $value_name;

        return $this;
    }

    public function getResponseName(): ?string
    {
        return $this->response_name;
    }

    public function setResponseName(?string $response_name): static
    {
        $this->response_name = $response_name;

        return $this;
    }

    public function isIsIncludedInTotalScore(): ?bool
    {
        return $this->is_included_in_total_score;
    }

    public function setIsIncludedInTotalScore(bool $is_included_in_total_score): static
    {
        $this->is_included_in_total_score = $is_included_in_total_score;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): static
    {
        $this->question = $question;

        return $this;
    }

    public function getResponse(): ?Response
    {
        return $this->response;
    }

    public function setResponse(?Response $response): static
    {
        $this->response = $response;

        return $this;
    }
}

src/Entity/TemplateQuestion.php
<?php

namespace App\Entity;

use App\Repository\TemplateQuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TemplateQuestionRepository::class)]
class TemplateQuestion
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?bool $requires_audio = false;

    #[ORM\Column]
    private ?bool $requires_text = false;

    #[ORM\Column]
    private ?bool $is_included_in_total_score = false;

    #[ORM\Column]
    private ?bool $is_mcq = false;

    #[ORM\Column]
    private ?bool $is_custom_score = false;

    #[ORM\Column(length: 255, nullable: false)]
    #[Assert\Length(
        min: 3,
        max: 254,
        minMessage: 'On doit préciser ce que chaque question évalue/renseigne.',
        maxMessage: 'Ce qui est évalué doit être désigné (Production de l\'enfant, niveau d\'aide...).'
    )]
    private ?string $instructions_fr;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $instructions_cr = null;

    #[ORM\ManyToOne(inversedBy: 'templateQuestions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Test $test = null;

    #[ORM\OneToMany(mappedBy: 'templateQuestion', targetEntity: TemplateValue::class, orphanRemoval: true, cascade: ['persist'])]
    private Collection $templateValues;

    #[ORM\OneToMany(mappedBy: 'templateQuestion', targetEntity: Question::class, orphanRemoval: true)]
    private Collection $questions;

    public function __construct()
    {
        $this->templateValues = new ArrayCollection();
        $this->questions = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }
    public function isRequiresAudio(): ?bool
    {
        return $this->requires_audio;
    }

    public function setRequiresAudio(bool $requires_audio): static
    {
        $this->requires_audio = $requires_audio;

        return $this;
    }

    public function isRequiresText(): ?bool
    {
        return $this->requires_text;
    }

    public function setRequiresText(bool $requires_text): static
    {
        $this->requires_text = $requires_text;

        return $this;
    }

    public function isIsIncludedInTotalScore(): ?bool
    {
        return $this->is_included_in_total_score;
    }

    public function setIsIncludedInTotalScore(bool $is_included_in_total_score): static
    {
        $this->is_included_in_total_score = $is_included_in_total_score;

        return $this;
    }

    public function isIsMcq(): ?bool
    {
        return $this->is_mcq;
    }

    public function setIsMcq(bool $is_mcq): static
    {
        $this->is_mcq = $is_mcq;

        return $this;
    }

    public function isIsCustomScore(): ?bool
    {
        return $this->is_custom_score;
    }

    public function setIsCustomScore(bool $is_custom_score): static
    {
        $this->is_custom_score = $is_custom_score;

        return $this;
    }

    public function getInstructionsFr(): ?string
    {
        return $this->instructions_fr;
    }

    public function setInstructionsFr(?string $instructions_fr): static
    {
        $this->instructions_fr = $instructions_fr;

        return $this;
    }

    public function getInstructionsCr(): ?string
    {
        return $this->instructions_cr;
    }

    public function setInstructionsCr(?string $instructions_cr): static
    {
        $this->instructions_cr = $instructions_cr;

        return $this;
    }

    public function getTest(): ?Test
    {
        return $this->test;
    }

    public function setTest(?Test $test): static
    {
        $this->test = $test;

        return $this;
    }

    /**
     * @return Collection<int, TemplateValue>
     */
    public function getTemplateValues(): Collection
    {
        return $this->templateValues;
    }

    public function addTemplateValue(TemplateValue $templateValue): static
    {
        if (!$this->templateValues->contains($templateValue)) {
            $this->templateValues->add($templateValue);
            $templateValue->setTemplateQuestion($this);
        }

        return $this;
    }

    public function removeTemplateValue(TemplateValue $templateValue): static
    {
        if ($this->templateValues->removeElement($templateValue)) {
            // set the owning side to null (unless already changed)
            if ($templateValue->getTemplateQuestion() === $this) {
                $templateValue->setTemplateQuestion(null);
            }
        }
        return $this;
    }
    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): static
    {
        if (!$this->questions->contains($question)) {
            $this->questions->add($question);
            $question->setTemplateQuestion($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): static
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getTemplateQuestion() === $this) {
                $question->setTemplateQuestion(null);
            }
        }

        return $this;
    }
}

src/Entity/TemplateValue.php
<?php

namespace App\Entity;

use App\Repository\TemplateValueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TemplateValueRepository::class)]
class TemplateValue
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $complete_name = null;

    #[ORM\Column]
    private ?int $score = null;

    #[ORM\ManyToOne(inversedBy: 'templateValues')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TemplateQuestion $templateQuestion = null;

    #[ORM\OneToMany(mappedBy: 'templateValue', targetEntity: OptionResponse::class, orphanRemoval: true, cascade: ['persist'])]
    private Collection $optionResponses;

    public function __construct()
    {
        $this->optionResponses = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }
    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCompleteName(): ?string
    {
        return $this->complete_name;
    }

    public function setCompleteName(?string $complete_name): static
    {
        $this->complete_name = $complete_name;

        return $this;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(int $score): static
    {
        $this->score = $score;

        return $this;
    }

    public function getTemplateQuestion(): ?TemplateQuestion
    {
        return $this->templateQuestion;
    }

    public function setTemplateQuestion(?TemplateQuestion $templateQuestion): static
    {
        $this->templateQuestion = $templateQuestion;

        return $this;
    }

    /**
     * @return Collection<int, OptionResponse>
     */
    public function getOptionResponses(): Collection
    {
        return $this->optionResponses;
    }

    public function addOptionResponse(OptionResponse $optionResponse): static
    {
        if (!$this->optionResponses->contains($optionResponse)) {
            $this->optionResponses->add($optionResponse);
            $optionResponse->setTemplateValue($this);
        }

        return $this;
    }

    public function removeOptionResponse(OptionResponse $optionResponse): static
    {
        if ($this->optionResponses->removeElement($optionResponse)) {
            // set the owning side to null (unless already changed)
            if ($optionResponse->getTemplateValue() === $this) {
                $optionResponse->setTemplateValue(null);
            }
        }

        return $this;
    }
}

src/Entity/Test.php
<?php

namespace App\Entity;

use App\Entity\Trait;
use App\Entity\Trait\ActiveTrait;
use App\Entity\Trait\SlugTrait;
use App\Repository\TestRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TestRepository::class)]
class Test
{
    use ActiveTrait;
    use SlugTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: 'Une épreuve doit obligatoirement avoir un nom')]
    #[Assert\Length(
        min: 5,
        max: 49,
        maxMessage: 'Le nom d\'une épreuve peut avoir {{ limit }} caractères au maximum.'
    )]
    private ?string $name = null;

    #[ORM\Column]
    private ?bool $is_timed = null;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero(message: 'Le temps à chronométrer ne peut pas être négatif')]
    private ?int $timer = null;

    #[ORM\Column(length: 800)]
    #[Assert\Length(
        min: 5,
        max: 800,
        maxMessage: 'La consigne d\'une épreuve peut avoir {{ limit }} caractères au maximum.'
    )]
    private ?string $instructions_fr = null;

    #[ORM\Column(length: 800, nullable: true)]
    private ?string $instructions_cr = null;

    #[ORM\Column(length: 800, nullable: true)]
    private ?string $implementation_advice = null;

    #[ORM\ManyToOne(inversedBy: 'tests')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TestType $typeTest = null;

    #[ORM\OneToMany(mappedBy: 'test', targetEntity: TemplateQuestion::class, cascade: ['persist'])]
    private Collection $templateQuestions;

    #[ORM\OneToMany(mappedBy: 'test', targetEntity: Item::class)]
    private Collection $items;

    #[ORM\OneToMany(mappedBy: 'test', targetEntity: Evaluation::class, orphanRemoval: true)]
    private Collection $evaluations;

    public function __construct()
    {
        $this->templateQuestions = new ArrayCollection();
        $this->items = new ArrayCollection();
        $this->evaluations = new ArrayCollection();
        $this->slug = transliterator_transliterate(
            'Any-Latin; Latin-ASCII; Lower()',
            $this->name
        );
        $this->is_timed = false;
        $this->active = false;
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function isIsTimed(): ?bool
    {
        return $this->is_timed;
    }

    public function setIsTimed(bool $is_timed): static
    {
        $this->is_timed = $is_timed;

        return $this;
    }

    public function getTimer(): ?int
    {
        return $this->timer;
    }

    public function setTimer(?int $timer): static
    {
        $this->timer = $timer;

        return $this;
    }

    public function getInstructionsFr(): ?string
    {
        return $this->instructions_fr;
    }

    public function setInstructionsFr(string $instructions_fr): static
    {
        $this->instructions_fr = $instructions_fr;

        return $this;
    }

    public function getInstructionsCr(): ?string
    {
        return $this->instructions_cr;
    }

    public function setInstructionsCr(?string $instructions_cr): static
    {
        $this->instructions_cr = $instructions_cr;

        return $this;
    }

    public function getImplementationAdvice(): ?string
    {
        return $this->implementation_advice;
    }

    public function setImplementationAdvice(?string $implementation_advice): static
    {
        $this->implementation_advice = $implementation_advice;

        return $this;
    }

    public function getTypeTest(): ?TestType
    {
        return $this->typeTest;
    }

    public function setTypeTest(?TestType $typeTest): static
    {
        $this->typeTest = $typeTest;

        return $this;
    }

    /**
     * @return Collection<int, TemplateQuestion>
     */
    public function getTemplateQuestions(): Collection
    {
        return $this->templateQuestions;
    }

    public function addTemplateQuestion(TemplateQuestion $templateQuestion): static
    {
        if (!$this->templateQuestions->contains($templateQuestion)) {
            $this->templateQuestions->add($templateQuestion);
            $templateQuestion->setTest($this);
        }

        return $this;
    }

    public function removeTemplateQuestion(TemplateQuestion $templateQuestion): static
    {
        if ($this->templateQuestions->removeElement($templateQuestion)) {
            // set the owning side to null (unless already changed)
            if ($templateQuestion->getTest() === $this) {
                $templateQuestion->setTest(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Item>
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): static
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
            $item->setTest($this);
        }

        return $this;
    }

    public function removeItem(Item $item): static
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getTest() === $this) {
                $item->setTest(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Evaluation>
     */
    public function getEvaluations(): Collection
    {
        return $this->evaluations;
    }

    public function addEvaluation(Evaluation $evaluation): static
    {
        if (!$this->evaluations->contains($evaluation)) {
            $this->evaluations->add($evaluation);
            $evaluation->setTest($this);
        }

        return $this;
    }

    public function removeEvaluation(Evaluation $evaluation): static
    {
        if ($this->evaluations->removeElement($evaluation)) {
            // set the owning side to null (unless already changed)
            if ($evaluation->getTest() === $this) {
                $evaluation->setTest(null);
            }
        }

        return $this;
    }
}

templates/item/_itemcardbody.html.twig
{% block body %}
	<h3 class="card-title">{{item.namefr | capitalize}}</h3>
	<ul class="list-group list-group-flush">
		{% if item.namecr %}
			<li class="list-group-item">
				Nom créole :
				{{item.namecr | capitalize}}
			</li>
		{% endif %}
		<li class="list-group-item">
			<label class="checkbox-inline">
				Actif
				<input onclick="" type="checkbox" checked data-toggle={{ item.active}}></label>
		</li>
		<li class="list-group-item">
			Épreuve associée :
			<p>
				<a href="{{ path('test_detail', {id : item.test.id})}}">{{ item.test.name | capitalize}}</a>
			</p>
		</li>
		{% if item.schoolgrade %}
			<li class="list-group-item">
				Niveau :
				<p>{{ item.schoolgrade.name}}</p>
			</li>
		{% endif %}
	</ul>
	<form action="{{ path('item_detail', {id: item.id})}}">
		<button type="submit" class="m-3 mt-0 btn btn-secondary">
			Détails
		</button>
	</form>
{% endblock %}

templates/item/_itemcardquestion.html.twig
{% block body %}

	{% if item.questions.count() > 0 %}
		<p>
			<strong>{{item.questions.count()}}
				questions sont posées pour cet item.</strong>
		</p>
		{% for question in item.questions %}
			<h4>{{question.templateQuestion.instructionsFr | capitalize}}</h4>
			{% if question.templateQuestion.instructionsCr %}
				<h4>{{question.templateQuestion.instructionsCr | capitalize}}</h4>
			{% endif %}
			{% if question.templateQuestion.isMCQ %}
				<table class="table">
					{% if question.optionResponses.count() > 1 %}
						<thead>
							<tr>
								<th scope="col">Nom de l'option</th>
								<th scope="col">Valeur</th>
								<th scope="col">Détail de la valeur</th>
								<th scope="col">Score associé</th>
							</tr>
						</thead>
						<tbody>
							{% for option in question.optionResponses %}
								<tr>
									<th>{{option.name | capitalize}}</th>
									<th>{{option.templateValue.name | capitalize}}</th>
									<th>{{option.templateValue.completeName | capitalize}}</th>
									<th>{{option.templateValue.score | capitalize}}</th>
								</tr>
							{% endfor %}
						{% endif %}
						{% if question.optionResponses.count() < 1 %}
							<thead>
								<tr>
									<th scope="col">Valeur</th>
									<th scope="col">Détail de la valeur</th>
									<th scope="col">Score associé</th>
								</tr>
							</thead>
							<tbody>
								{% for option in question.templateQuestion.templateValues %}
									<tr>
										<th>{{option.name | capitalize}}</th>
										<th>{{option.completeName | capitalize}}</th>
										<th>{{option.score | capitalize}}</th>
									</tr>
								{% endfor %}
							{% endif %}
						</tbody>
					</table>
					{% if app.request.attributes.get('_route') == 'admin_item_edit' %}
						<a href="{{ path('admin_question_edit', {'id': question.id}) }}" class="m-3 mt-0 btn btn-outline-primary">
							Personnaliser les options de réponse pour cette question et cet item
						</a>
					{% endif %}
				{% endif %}
				{% if question.templateQuestion.requiresText %}
					<p>Texte à saisir</p>
				{% endif %}
				{% if question.templateQuestion.requiresAudio %}
					<p>Un fichier audio doit être enregistré</p>
				{% endif %}
				{% if question.templateQuestion.requiresAudio %}
					<p>Un fichier audio doit être enregistré</p>
				{% endif %}
				{% if question.templateQuestion.isCustomScore %}
					<p>Un score doit être manuellement saisi</p>
				{% endif %}
				{% if question.templateQuestion.isIncludedInTotalScore %}
					<p>Ce score est pris en compte dans le calcul du score total de l'épreuve.</p>
				{% else %}
					<p>Ce score n'est pas pris en compte dans le calcul du score total de l'épreuve.</p>
				{% endif %}
			{% endfor %}
		{% endif %}
	{% endblock %}

templates/item/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Béocler - Item
	{{ item.namefr | capitalize }}
{% endblock %}

{% block body %}
	<div class="container mt-5">
		<div class="row">
			<div class="col-12">
				<h1>Détail de l'item
					{{ item.namefr }}</h1>
			</div>
			<div class="card col-12 col-md-5 mt-5">
				<h3>Détails de l'item</h3>
				<div class="card-body">
					<label class="checkbox-inline">
						<h3>Actif</h3>
						<input onclick="" type="checkbox" checked data-toggle="{{ item.active }}">
					</label>
					<h3>Épreuve associée</h3>
					<p>
						<a href="{{ path('test_detail', {id : item.test.id}) }}">{{ item.test.name | capitalize }}</a>
					</p>
					<h3>Nom en français</h3>
					<p>{{ item.namefr | capitalize }}</p>
					{% if item.namecr %}
						<h3>Nom en créole</h3>
						<p>{{ item.namecr | capitalize }}</p>
					{% endif %}
					{% if item.schoolgrade %}
						<h3>Niveau scolaire minimum</h3>
						<p>{{ item.schoolgrade.name }}</p>
					{% endif %}
				</div>
			</div>
			{% if item.illustrations.count() > 0 %}
				<div class="card col-12 col-md-7 mt-5">
					<div id="carouselItemIllustrations" class="carousel slide" data-bs-ride="carousel">
						<h3>Illustrations de l'item</h3>
						<div class="carousel-indicators">
							{% for iteration in 1..item.illustrations|length %}
								<button type="button" data-bs-target="#carouselItemIllustrations" data-bs-slide-to="{{ iteration - 1 }}" {{ (loop.first) ? 'class="active" aria-current="true"' : '' }} aria-label="Slide {{ iteration }}"></button>
							{% endfor %}
						</div>
						<div class="carousel-inner">
							{% for illustration in item.illustrations %}
								<div class="carousel-item {{ (loop.first) ? 'active center-active' : '' }}">
									<img src="{{ asset('images/uploads/item/mini/500x500-' ~ illustration.path) }}" alt="{{ 'illustration500x500-' ~ illustration.item.namefr }}" width="350"/>
								</div>
							{% endfor %}
						</div>
						<button class="carousel-control-prev" type="button" data-bs-target="#carouselItemIllustrations" data-bs-slide="prev">
							<span class="carousel-control-prev-icon" aria-hidden="true"></span>
							<span class="visually-hidden">Previous</span>
						</button>
						<button class="carousel-control-next" type="button" data-bs-target="#carouselItemIllustrations" data-bs-slide="next">
							<span class="carousel-control-next-icon" aria-hidden="true"></span>
							<span class="visually-hidden">Next</span>
						</button>
					</div>
				</div>
			{% endif %}
			<div class="card col-12 mt-5">
				<div class="card-body">
					<h3 class="card-title">Questions associées à cet item</h3>
					{% include "/item/_itemcardquestion.html.twig" %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/item/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Béocler - Liste des items
{% endblock %}
{% block body %}
<div class="container m-5">
	<div class="row">
		<h1>Liste des items</h1>
		{% for item in items %}
			<div class="card h-100 col-3">
				{% if item.illustrations.count() > 0%}
					<img src="{{ asset('images/uploads/item/mini/500x500-' ~ item.illustrations[0].path ) }}" alt="{{ 'illustration500x500-' ~ item.illustrations[0].item.namefr}}" width="150">
				{% endif %}
				<div class="card-body">
					{% include "/item/_itemcardbody.html.twig"%}</div>
			</div>
		{% endfor %}
	</div>
</div {% endblock %}